### ISSUE TITLE
Build issues on macos Monterey

### ISSUE THREAD

**Issue by moeller0** [network-quality/goresponsiveness#38]
When trying to update the newest version I see the following issue:
```
ash-3.2$ date
Sun Aug 28 14:21:13 CEST 2022
bash-3.2$ git pull
Already up to date.
bash-3.2$ go mod download
bash-3.2$ go build networkQuality.go
# github.com/network-quality/goresponsiveness/rpm
rpm/rpm.go:203:33: undefined: extendedstats.GetTCPInfo
```

**Comment by mcr-ksh** [comment]
same here on go1.19

**Comment by hawkinsw** [comment]
Sorry everyone!! All fixed with a4cabcf65b099b67747569b33fe43c345ea317ad! Let me know if that fixes you and I will close the issue! Sorry again @mcr-ksh and @moeller0 !!

**Comment by moeller0** [comment]
Thanks, this fixes it. I tried with a bit of slash and hack, but I am realizing I need to read up a bit on go, before I should touch the code.

**Comment by hawkinsw** [comment]
We are a welcoming bunch here -- if you ever want to drop a patch, we'd
love it!!

Given your feedback, I will close the issue! Thanks for reporting and
sorry, again, about the trouble!

Will

**Comment by moeller0** [comment]
Oh, sorry, yes I will close it.

**Comment by hawkinsw** [comment]
> Oh, sorry, yes I will close it.

I am *really* sorry -- I did not mean to imply that I was asking you to close it! I just wanted to confirm with you that you thought it was okay to close it. You were the original reporter and I didn't want to presume to have solved your problem with your confirmation. 

I hope that my message didn't come off "jerky". I am really sorry!

Will

**Comment by moeller0** [comment]
Oh, no your proposal was just fine, it just reminded me that the issue is solved in the best possible way and that I should have closed it after confirming the fix "fixed" it.

**Comment by hawkinsw** [comment]
Thank you! We are on it!!

Will
