### ISSUE TITLE
Responsiveness (Low, Medium, High) - What is a "good" connection? [Human Factors]

### ISSUE THREAD

**Issue by m33x** [network-quality/goresponsiveness#40]
Hi, 

wonderful project. Thank you!

I wonder why the macOS version of the tool reports human labels for the responsiveness like "Low" / "Medium" / "High" but the open-source version does not? I would love to use the tool to decide whether or not I need to reboot my consumer-grade cabel modem (which usually fixes my bad Internet). For me, it is hard to tell what a good connection and what a bad connection is.

Based on this [thread](https://www.tonymacx86.com/threads/macos-built-in-speed-test-post-your-network-speed.319813/), I came up with the following thresholds (for Apple's mensura.cdn-apple.com server). Are they correct?

```
Low (0-199 RPM)
Medium (200-999 RPM)
High (1000-inf RPM)
```

The numbers I observed in the thread:
```
Responsiveness: Low (0 RPM)
Responsiveness: Low (57 RPM)
..
Responsiveness: Low (183 RPM)
--> Looks like 200 is the magic constant
Responsiveness: Medium (206 RPM)
Responsiveness: Medium (249 RPM)
...
Responsiveness: Medium (980 RPM)
Responsiveness: Medium (993 RPM)
--> Looks like 1000 is the magic constant
Responsiveness: High (1060 RPM)
Responsiveness: High (1072 RPM)
...
Responsiveness: High (7619 RPM)
Responsiveness: High (10105 RPM)
```

**networkQuality** output on **macOS**:
```
$> networkQuality -v
==== SUMMARY ====
Upload capacity: 477.431 Mbps
Download capacity: 871.854 Mbps
Upload flows: 20
Download flows: 12
Responsiveness: High (3465 RPM)
Base RTT: 11
Start: 7/12/22, 11:30:38 AM
End: 7/12/22, 11:30:53 AM
OS Version: Version 12.4 (Build 21F79)
```

**networkQuality** output **open-source version**:
```
$> networkQuality --config mensura.cdn-apple.com --port 443 --path /api/v1/gm/config
09-27-2022 16:35:25 UTC Go Responsiveness to mensura.cdn-apple.com:443...
Download:  84.760 Mbps ( 10.595 MBps), using 12 parallel connections.
Upload:    56.637 Mbps (  7.080 MBps), using 28 parallel connections.
RPM:  3407
```
(The two measurments are unrelated)

**Comment by hawkinsw** [comment]
@m33x Thanks for the comment and *sorry* for the delay responding! You have asked a *great* question and I spoke with @cpaasch during our weekly meeting about this very issue. We intentionally did not specify these three levels in the specification because we hope that the values will continually improve as more and more network operators begin addressing buffer bloat. In fact, in versions of the network quality tool in macOS that are available in the beta now have removed the "quality" label. I hope that this helps! 

Let me know if you have any other questions -- thanks again for your interest! Please keep us posted if there are other ways that you want to contribute! We'd love to have you!
Will

**Comment by m33x** [comment]
Thanks for the clarification. I understand and respect your decision.

From my experience (taken from the space of password strength meters), these noble motives will ultimately hinder the adoption and deployment. People are not willing to spend 10 minutes figuring this stuff out. Usually, it's way simpler: run it, if it works, great, if not, try another tool / approach.

Thus, I highly recommend you to add guidelines to the standard/tool that will at least describe the state-of-the-art as of 2022. Ofc you can add a red note highlighting the fact that the values are subject to change and not representative (as networks will improve in the future and are very different across countries etc.), but whether this change will come soon, next year, or in 10 years or even in 20 years, nobody knows.

Anyway, thanks a lot for your help and the explanation.

**Comment by hawkinsw** [comment]
Great feedback! I really appreciate it! I am flagging @cpaasch and @StuartCheshire to get their perspective! Thanks again, @m33x!
