### ISSUE TITLE
Relicensing as GPLv2

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/goresponsiveness#41]
Hello everyone (i.e., @acohn @richb-hanover @Schickendantzj ) ! I would like to relicense the go-based client as GPLv2. As contributors, I wanted to get your signoff! I am hoping that a switch to GPLv2 will give some other contributors the option to participate. If you are okay with the switch, we will go forward. 

Feel free to drop a comment on this issue -- I am happy to discuss, of course!!

Thanks again, everyone, for your awesome contributions and I hope that we can keep up this momentum!! 

Sincerely,
Will

**Comment by acohn** [comment]
Relicensing as GPL2 is fine by me.

**Comment by Schickendantzj** [comment]
Same here!

**Comment by hawkinsw** [comment]
> Same here!

Thank you!!

**Comment by richb-hanover** [comment]
Relicensing at GPL2 is fine by me.

**Comment by hawkinsw** [comment]
Closing per 1f36afaf4e2c79aa4bc80f9bc8320ea28cc51f6f
