### ISSUE TITLE
[parallel_testing] unexpected error

### ISSUE THREAD

**Issue by moeller0** [network-quality/goresponsiveness#63]
```
user@1234-12345:~/CODE/goresponsiveness$ ./networkQuality --relative-rpm --rpm.parallel --config mensura.cdn-apple.com --port 443 --path /api/v1/gm/config --extended-stats --logger-filename go_networkQuality_20231229_122853_vanilla
12-30-2023 08:23:28 UTC Go Responsiveness to mensura.cdn-apple.com:443...
Baseline RPM:  2462 (P90)
Baseline RPM:  4083 (Single-Sided 5% Trimmed Mean)
Warning: Throughput stability could not be reached. Making the test 15 seconds longer to calculate speculative RPM results.
Warning: Throughput stability could not be reached. Making the test 15 seconds longer to calculate speculative RPM results.
panic: runtime error: index out of range [18446744073709551615] with length 0

goroutine 5041 [running]:
github.com/network-quality/goresponsiveness/series.(*windowSeriesForeverImpl[...]).Reserve(0x8467e0, 0x203)
	/home/user/CODE/goresponsiveness/series/series.go:239 +0x1bf
main.main.func6()
	/home/user/CODE/goresponsiveness/networkQuality.go:851 +0x198a
github.com/network-quality/goresponsiveness/executor.Execute.func1()
	/home/user/CODE/goresponsiveness/executor/executor.go:39 +0x23
created by github.com/network-quality/goresponsiveness/executor.Execute in goroutine 1
	/home/user/CODE/goresponsiveness/executor/executor.go:44 +0xd8
user@12345-horse:~/CODE/goresponsiveness$ 
```
Not sure what this is, so far I only saw this once...

**Comment by hawkinsw** [comment]
Thank you!! I have not seen this error but I know what is the likely cause ... I will investigate asap!!

**Comment by hawkinsw** [comment]
I see why the error happens! It is because of an out-of-order start. A good solution to this problem will require a small refactor -- one that is long overdue. I will do that sometime this evening and I will post a fix! Sorry for the problem!

**Comment by hawkinsw** [comment]
Should be fixed in the latest version of the parallel_testing branch. I will leave this open for @moeller0 to close once we have given this a thorough checking!

**Comment by moeller0** [comment]
I have not been able to make this come up again with the last two versions, so I will close this. In case it simply got rarer and will show up again, shall I re-open this issue or open a new one (I hope that this is a theoretical question)

**Comment by hawkinsw** [comment]
> I have not been able to make this come up again with the last two versions, so I will close this. In case it simply got rarer and will show up again, shall I re-open this issue or open a new one (I hope that this is a theoretical question)

Thanks!!
